BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

SET DATEFORMAT dmy;

UPDATE [dbo].[candidati] 
SET 
	InterviewDate=CONVERT(DATE, RTRIM(LTRIM(colloquio)), 105),
	BirthDate=CONVERT(DATE, CASE WHEN ISDATE(RTRIM(LTRIM(anno))) = 1 THEN RTRIM(LTRIM(anno)) ELSE '01/01/0001' END, 105),
	UpdateDate=CONVERT(DATE, CASE WHEN ISDATE(RTRIM(LTRIM(aggiornamento))) = 1 AND aggiornamento <> '1/1/1980'  THEN RTRIM(LTRIM(aggiornamento)) ELSE '01/01/0001' END, 105)
;

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;