BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[Options]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[Section] INT NOT NULL, 
    [SerializedValue] VARCHAR(1000) NOT NULL, 
    [IsDeleted] BIT NOT NULL DEFAULT 0 
)

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
