BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

ALTER TABLE [dbo].[candidati] 
	ADD [UpdateDate] DATE NULL;

ALTER TABLE [dbo].[candidati] 
	ADD [BirthDate] DATE NULL;

ALTER TABLE [dbo].[candidati] 
	ADD [InterviewDate] DATE NULL;

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
