BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[mhreportlock]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserId] INT NOT NULL, 
    [Month] VARCHAR(6) NOT NULL, 
    [LockDate] DATETIME NOT NULL, 
	[UnlockDate] DATETIME NULL, 
    [IsDeleted] BIT NULL
);

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
