BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[rappvociretributive]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserId] INT NOT NULL,
	[Month] VARCHAR(6) NOT NULL, 
    [Type] INT NOT NULL, 
    [Qty] INT NOT NULL, 
	[Amount] DECIMAL NULL,
	[Total] DECIMAL NULL
);

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
