BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[export]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
	[month] VARCHAR(6) NOT NULL, 
    [mhFileName] VARCHAR(50) NOT NULL, 
	[riFileName] VARCHAR(50) NOT NULL,
    [usersCount] INT NOT NULL, 
    [usersMax] INT NOT NULL, 
    [calculateDate] DATETIME NOT NULL
);

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
