BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

SET DATEFORMAT dmy;

ALTER TABLE [dbo].[candidati] WITH NOCHECK
    ADD CONSTRAINT [FK_candidati_utenti] FOREIGN KEY ([idselezionatore]) REFERENCES [dbo].[utenti] ([idutente]);

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;