BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

SET DATEFORMAT dmy;

ALTER TABLE [dbo].[utenti]
    ADD CONSTRAINT [PK_utenti] PRIMARY KEY CLUSTERED ([idutente] ASC);

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;