BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

SET DATEFORMAT dmy;

UPDATE [dbo].[candidati] 
SET 
	InterviewDate=CONVERT(DATE, '01/01/0001', 105)
WHERE
	RTRIM(LTRIM(colloquio)) = '1/1/1980';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;