BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

ALTER TABLE [dbo].[export] 
	ADD [HourReport] VARCHAR(1000) NULL;


ALTER TABLE [dbo].[export] 
	ADD [RetributionItems] VARCHAR(1000) NULL;


COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
