[
{
    password: "P13rp4",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 38,
    username: "AielloMS",
    firstname: "Pierpaolo",
    lastname: "Aiello",
    company: "COMPANY",
    name: "Pierpaolo Aiello",
    picture: "https://unsplash.it/48/48?image=38"
},
{
    password: "GiorgioA2014",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 30,
    username: "GAugelli",
    firstname: "Giorgio",
    lastname: "Augelli",
    company: "COMPANY",
    name: "Giorgio Augelli",
    picture: "https://unsplash.it/48/48?image=30"
},
{
    password: "Luc4B0n1",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 37,
    username: "B0n1f4c10",
    firstname: "Luca",
    lastname: "Bonifacio",
    company: "COMPANY",
    name: "Luca Bonifacio",
    picture: "https://unsplash.it/48/48?image=37"
},
{
    password: "C6iroli",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 7,
    username: "ValerioC",
    firstname: "Valerio",
    lastname: "Cairoli",
    company: "COMPANY",
    name: "Valerio Cairoli",
    picture: "https://unsplash.it/48/48?image=7"
},
{
    password: "PortaPenne4",
    _sectionusersvisible: 1,
    _sectionjobadsvisible: 1,
    _sectionmonthlyreportsvisible: 1,
    _sectionjobapplicantsvisible: 1,
    _isactive: 1,
    sectionusersvisible: true,
    sectionjobadsvisible: true,
    sectionmonthlyreportsvisible: true,
    sectionjobapplicantsvisible: true,
    isactive: true,
    id: 4,
    username: "DavideC86",
    firstname: "Davide",
    lastname: "Cavalli",
    company: "COMPANY",
    name: "Davide Cavalli",
    picture: "https://unsplash.it/48/48?image=4"
},
{
    password: "Ch4ck0",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 39,
    username: "SimiCH",
    firstname: "Simi",
    lastname: "Chacko",
    company: "COMPANY",
    name: "Simi Chacko",
    picture: "https://unsplash.it/48/48?image=39"
},
{
    password: "Colomb9",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 11,
    username: "MarcoC",
    firstname: "Marco",
    lastname: "Colombo",
    company: "COMPANY",
    name: "Marco Colombo",
    picture: "https://unsplash.it/48/48?image=11"
},
{
    password: "L0un1s",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 35,
    username: "Djenn4d1",
    firstname: "Lounis",
    lastname: "Djennadi",
    company: "COMPANY",
    name: "Lounis Djennadi",
    picture: "https://unsplash.it/48/48?image=35"
},
{
    password: "Gagn1",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 1,
    _sectionmonthlyreportsvisible: 1,
    _sectionjobapplicantsvisible: 1,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: true,
    sectionmonthlyreportsvisible: true,
    sectionjobapplicantsvisible: true,
    isactive: true,
    id: 21,
    username: "nandowalter",
    firstname: "Fernando Walter",
    lastname: "Gagni",
    company: "COMPANY",
    name: "Fernando Walter Gagni",
    picture: "https://unsplash.it/48/48?image=21"
},
{
    password: "4ndre4",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 33,
    username: "Germ4n1",
    firstname: "Andrea",
    lastname: "Germani",
    company: "COMPANY",
    name: "Andrea Germani",
    picture: "https://unsplash.it/48/48?image=33"
},
{
    password: "IAQUINTA88",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 43,
    username: "SimoneIA",
    firstname: "Simone",
    lastname: "Iaquinta",
    company: "COMPANY",
    name: "Simone Iaquinta",
    picture: "https://unsplash.it/48/48?image=43"
},
{
    password: "Rob3rt0",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 18,
    username: "Marelli",
    firstname: "Roberto",
    lastname: "Marelli",
    company: "COMPANY",
    name: "Roberto Marelli",
    picture: "https://unsplash.it/48/48?image=18"
},
{
    password: "Giada2008C",
    _sectionusersvisible: 1,
    _sectionjobadsvisible: 1,
    _sectionmonthlyreportsvisible: 1,
    _sectionjobapplicantsvisible: 1,
    _isactive: 1,
    sectionusersvisible: true,
    sectionjobadsvisible: true,
    sectionmonthlyreportsvisible: true,
    sectionjobapplicantsvisible: true,
    isactive: true,
    id: 3,
    username: "MiticaMicky",
    firstname: "Michela",
    lastname: "Merlo",
    company: "COMPANY",
    name: "Michela Merlo",
    picture: "https://unsplash.it/48/48?image=3"
},
{
    password: "St3fan0",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 32,
    username: "S_Pompei",
    firstname: "Stefano",
    lastname: "Pompei",
    company: "COMPANY",
    name: "Stefano Pompei",
    picture: "https://unsplash.it/48/48?image=32"
},
{
    password: "Pretti1",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 8,
    username: "StefanoP",
    firstname: "Stefano",
    lastname: "Pretti",
    company: "COMPANY",
    name: "Stefano Pretti",
    picture: "https://unsplash.it/48/48?image=8"
},
{
    password: "Alfr3d0",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 40,
    username: "Ranchett1A",
    firstname: "Alfredo",
    lastname: "Ranchetti",
    company: "COMPANY",
    name: "Alfredo Ranchetti",
    picture: "https://unsplash.it/48/48?image=40"
},
{
    password: "ValentinaRuga90",
    _sectionusersvisible: 1,
    _sectionjobadsvisible: 1,
    _sectionmonthlyreportsvisible: 1,
    _sectionjobapplicantsvisible: 1,
    _isactive: 1,
    sectionusersvisible: true,
    sectionjobadsvisible: true,
    sectionmonthlyreportsvisible: true,
    sectionjobapplicantsvisible: true,
    isactive: true,
    id: 42,
    username: "ValeR",
    firstname: "Valentina",
    lastname: "Ruga",
    company: "COMPANY",
    name: "Valentina Ruga",
    picture: "https://unsplash.it/48/48?image=42"
},
{
    password: "SSu4rez",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 41,
    username: "LuisSanviti",
    firstname: "Luis Alberto",
    lastname: "Sanviti Suarez",
    company: "COMPANY",
    name: "Luis Alberto Sanviti Suarez",
    picture: "https://unsplash.it/48/48?image=41"
},
{
    password: "Sc1olt1",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 10,
    username: "FrancescoS",
    firstname: "Francesco",
    lastname: "Sciolti",
    company: "COMPANY",
    name: "Francesco Sciolti",
    picture: "https://unsplash.it/48/48?image=10"
},
{
    password: "G1us3pp3",
    _sectionusersvisible: 0,
    _sectionjobadsvisible: 0,
    _sectionmonthlyreportsvisible: 0,
    _sectionjobapplicantsvisible: 0,
    _isactive: 1,
    sectionusersvisible: false,
    sectionjobadsvisible: false,
    sectionmonthlyreportsvisible: false,
    sectionjobapplicantsvisible: false,
    isactive: true,
    id: 36,
    username: "Sc0rd0",
    firstname: "Giuseppe",
    lastname: "Scordo",
    company: "COMPANY",
    name: "Giuseppe Scordo",
    picture: "https://unsplash.it/48/48?image=36"
}
]